version: 1

before:
  hooks:
    - go mod tidy

builds:
  - 
    id: "nex"
    main: "./nex"
    binary: "nex"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows 
        goarch: arm
    ldflags:
      - -s -w --X main.VERSION={{.Version}} -X main.COMMIT={{.Commit}} -X main.BUILDDATE={{.Date}}
      - -extldflags "-static"
    tags:
      - netgo
      - withui
    hooks:
      pre:
        - go run ./ui/web/build/main.go ./ui/web
  -
    id: "agent"
    main: "./agent/cmd/nex-agent"
    binary: "nex-agent"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w --X main.VERSION={{.Version}} -X main.COMMIT={{.Commit}} -X main.BUILDDATE={{.Date}}
      - -extldflags "-static"
    tags:
      - netgo
    hooks:
      post:
        - sudo go run ./agent/fc-image/. {{.Path}} 

archives:
  - id: binaries
    format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: rootfs
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    files:
      - rootfs.ext4

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
