version: 1

before:
  hooks:
    - go mod tidy

builds:
  - 
    id: "nex"
    main: "./nex"
    binary: "nex"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows 
        goarch: arm
    ldflags:
      - -s -w --X main.VERSION={{.Version}} -X main.COMMIT={{.Commit}} -X main.BUILDDATE={{.Date}} -X github.com/synadia-io/nex/internal/node.VERSION={{.Version}} -X github.com/synadia-io/nex/internal/node.COMMIT={{.Commit}} -X github.com/synadia-io/nex/internal/node.BUILDDATE={{.Date}}
      - -extldflags "-static"
    tags:
      - netgo
  -
    id: "agent"
    main: "./agent/cmd/nex-agent"
    binary: "nex-agent"
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w --X github.com/synadia-io/nex/agent.VERSION={{.Version}} -X github.com/synadia-io/nex/agent.COMMIT={{.Commit}} -X github.com/synadia-io/nex/agent.BUILDDATE={{.Date}}
      - -extldflags "-static"
    tags:
      - netgo
    hooks:
      post:
        - sudo go run ./nex/. fs --agent {{.Path}}

archives:
  - id: binaries
    format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    allow_different_binary_count: true

nfpms:
  - id: linux_packages
    homepage: https://docs.nats.io/using-nats/nex
    maintainer: Synadia Communications
    description: |-
      The NATS execution engine
    license: Apache 2.0
    formats:
      - deb 
      - rpm

release:
  extra_files:
    - glob: ./rootfs.ext4.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
