# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "nex"

tasks:
  agent-api:
    dir: agent-api
    sources:
      - "*.proto"
    generates:
      - "*.pb.go"
    cmds:
      - protoc --proto_path=./ --go_out=./ --go_opt=paths=source_relative --go-grpc_out=./ --go-grpc_opt=paths=source_relative ./*.proto

  nex-agent:
    dir: nex-agent/cmd/nex-agent
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  nex-node:
    dir: nex-node/cmd/nex-node
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  nex-cli:
    dir: nex-cli/cmd/nex
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  echo-service:
    dir: examples/echoservice
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  gen:
    deps: [agent-api]

  build:
    deps: [nex-agent, nex-node, nex-cli, echo-service]