# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "nex"

tasks:  
  agent:
    dir: agent/cmd/nex-agent
    sources:
      - "*.go"
    cmds:
#      - go build -tags netgo -ldflags '-extldflags "-static"'
      - go build

  clean:
    cmds:
      - rm -f nex/nex
      - rm -f rootfs.ext4.gz
      - sudo rm -rf /opt/cni/bin/*
      - sudo rm -rf /var/lib/cni/*
      - sudo rm -rf /etc/cni/conf.d/*
      - sudo rm -f /tmp/rootfs-*
      - sudo rm -f /tmp/.firecracker.*
      - sudo rm -rf /tmp/pnats
      - sudo rm -f /tmp/*.js
      - sudo rm -rf /tmp/*-spec
      - sudo rm -rf /tmp/*-spec-nex-conf.json
      - sudo rm -rf /tmp/*-spec-nex-wd
      - sudo rm -rf /tmp/rootfs-*.ext4
      - sudo rm -rf /tmp/*-rootfs.ext4

  nex:
    dir: nex
    sources:
      - "*.go"
    cmds:
#      - go build -tags netgo -ldflags '-extldflags "-static"'
    - go build

  rootfs:
    dir: nex
    sources:
      - "*.go"
    cmds:
      - sudo ./nex fs --agent ../agent/cmd/nex-agent/nex-agent
      - gunzip rootfs.ext4.gz
    deps:
      [agent, nex]

  noop-workload-provider:
    dir: examples/workload_provider_plugins/noop
    sources:
      - "*.go"
    cmds:    
      - go build -buildmode=plugin

  noop-hostservice-provider:
    dir: examples/host_services_plugins/noop
    sources:
      - "*.go"
    cmds:
      - go build -buildmode=plugin

  echo-service:
    dir: examples/echoservice
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  unit-test:
    deps: [clean]
    cmds:
      - go test $(go list ./... | grep -v spec)

  test:
    deps: [clean, agent]
    cmds:         
      - sudo go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --vv --trace --keep-going ./spec #--cover --coverprofile=.coverage-report.out
      - mv spec _spec
      - go test -tags netgo -ldflags '-extldflags "-static"'-v -race ./...
      - mv _spec spec
  
  otel_start:
    dir: _scripts/otel
    cmds:
      - docker compose up -d
  
  otel_stop:
    dir: _scripts/otel
    cmds:
      - docker compose down

  build:
    deps: [agent, nex, echo-service]
