# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "nex"

tasks:  
  agent:
    dir: agent/cmd/nex-agent
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  clean:
    cmds:
      - rm -f nex/nex
      - rm -f rootfs.ext4.gz
      - sudo rm -rf /opt/cni/bin/*
      - sudo rm -rf /var/lib/cni/*
      - sudo rm -rf /etc/cni/conf.d/*
      - sudo rm -f /tmp/rootfs-*
      - sudo rm -f /tmp/.firecracker.*
      - sudo rm -rf /tmp/pnats
      - sudo rm -f /tmp/*.js
      - sudo rm -rf /tmp/*-spec
      - sudo rm -rf /tmp/*-spec-nex-conf.json
      - sudo rm -rf /tmp/*-spec-nex-wd
      - sudo rm -rf /tmp/rootfs-*.ext4
      - sudo rm -rf /tmp/*-rootfs.ext4

  nex:
    dir: nex
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  rootfs:
    dir: agent/fc-image
    sources:
      - "*.go"
    cmds:
      - sudo /usr/local/go/bin/go run . ../cmd/nex-agent/nex-agent
      - gunzip rootfs.ext4.gz
    deps:
      [agent]

  echo-service:
    dir: examples/echoservice
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  test:
    deps: [clean, agent]
    cmds:
      - sudo go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --vv --trace --keep-going ./spec #--cover --coverprofile=.coverage-report.out
      - go test -tags netgo -ldflags '-extldflags "-static"'-v -race ./test

  build:
    deps: [agent, ui, nex, echo-service]
