# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "nex"

tasks:  
  agent:
    dir: agent/cmd/nex-agent
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  nex:
    dir: nex
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo,withui -ldflags '-extldflags "-static"'

  echo-service:
    dir: examples/echoservice
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  ui:
    dir: ui/web
    cmds:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - pnpm install
      - pnpm build

  build:
    deps: [agent, ui, nex, echo-service]
