version: '3'

tasks:
  # requires the protoc binary in the path, and the `protoc-gen-go` plugin
  # 'go install google.golang.org/protobuf/cmd/protoc-gen-go@latest'

  proto:
    dir: node/actors/pb
    sources:
      - "*.proto"
    generates:
      - "*.go"
    cmds:
      - protoc --proto_path=. --go_out=. --go_opt=paths=source_relative *.proto
  
  nex:
    deps: [proto]
    dir: cmd/nex
    cmds:
      - go build .
