# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "nex"

tasks:  
  agent:
    dir: agent/cmd/nex-agent
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  clean:
    cmds:
      - rm -f nex/nex
      - rm -f rootfs.ext4.gz
      - sudo rm -rf /opt/cni/bin/*
      - sudo rm -rf /var/lib/cni/*
      - sudo rm -rf /etc/cni/conf.d/*
      - sudo rm -f /tmp/rootfs-*
      - sudo rm -f /tmp/.firecracker.*
      - sudo rm -rf /tmp/pnats
      - sudo rm -f /tmp/*.js
      - sudo rm -rf /tmp/*-spec
      - sudo rm -rf /tmp/*-spec-nex-conf.json
      - sudo rm -rf /tmp/*-spec-nex-wd
      - sudo rm -rf /tmp/rootfs-*.ext4
      - sudo rm -rf /tmp/*-rootfs.ext4

  nex:
    dir: nex
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo,withui -ldflags '-extldflags "-static"'

  echo-service:
    dir: examples/echoservice
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'

  test:
    deps: [clean]
    cmds:
      - sudo $GOPATH/bin/ginkgo run -r --randomize-all --vv --trace --keep-going ./spec #--cover --coverprofile=.coverage-report.out
      - go test -v -race ./test

  ui:
    dir: ui/web
    cmds:
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - pnpm install
      - pnpm build

  build:
    deps: [agent, ui, nex, echo-service]
