version: '3'

tasks:
  # requires the protoc binary in the path, and the `protoc-gen-go` plugin
  # 'go install google.golang.org/protobuf/cmd/protoc-gen-go@latest'

  proto:
    dir: node/actors/pb
    sources:
      - "*.proto"
    generates:
      - "*.go"
    cmds:
      - protoc --proto_path=. --go_out=. --go_opt=paths=source_relative *.proto

  all-code-gen:
    deps: [gen-schema, proto]

  gen-schema:
    deps: [gen-schema-nodecontrol, gen-schema-agent]

  gen-schema-agent:
    dir: api/agent/go
    cmds:
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/api/agent/register-agent-request=github.com/synadia-io/nex/agentapi/go/gen \
      --schema-output=https://github.com/synadia-io/nex/api/agent/register-agent-request=gen/register_agent_request.go \
       ../register-agent-request.json"
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/api/agent/start-workload-request=github.com/synadia-io/nex/api/agent/go/gen \
      --schema-output=https://github.com/synadia-io/nex/api/agent/start-workload-request=gen/start_workload_request.go \
       ../start-workload-request.json"
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/api/agent/stop-workload-request=github.com/synadia-io/nex/agentapi/go/gen \
      --schema-output=https://github.com/synadia-io/nex/api/agent/stop-workload-request=gen/stop_workload_request.go \
       ../stop-workload-request.json"
  
  gen-schema-nodecontrol:
    dir: api/nodecontrol
    cmds:
      - "go-jsonschema \
      --package=gen -o=./gen/auction_request.go \
      --schema-package=io.nats.nex.v2.auction-request=github.com/synadia-io/nex/api/nodecontrol/gen \
      auction-request.json"
      - "go-jsonschema \
      --package=gen -o=./gen/auction_response.go \
      --schema-package=io.nats.nex.v2.auction-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      auction-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/node_ping_response.go \
      --schema-package=io.nats.nex.v2.node-ping-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      node-ping-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/agent_ping_response.go \
      --schema-package=io.nats.nex.v2.agent-ping-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      agent-ping-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/lameduck_response.go \
      --schema-package=io.nats.nex.v2.lame-duck-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      lameduck-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/node_info_response.go \
      --schema-package=io.nats.nex.v2.node-info-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      node-info-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/stop_workload_request.go \
      --schema-package=io.nats.nex.v2.stop-workload-request=github.com/synadia-io/nex/api/nodecontrol/gen \
      stop-workload-request.json"
      - "go-jsonschema \
      --package=gen -o=./gen/stop_workload_response.go \
      --schema-package=io.nats.nex.v2.stop-workload-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      stop-workload-response.json"
      - "go-jsonschema \
      --package=gen -o=./gen/start_workload_request.go \
      --schema-package=io.nats.nex.v2.start-workload-request=github.com/synadia-io/nex/api/nodecontrol/gen \
      start-workload-request.json"
      - "go-jsonschema \
      --package=gen -o=./gen/start_workload_response.go \
      --schema-package=io.nats.nex.v2.start-workload-response=github.com/synadia-io/nex/api/nodecontrol/gen \
      start-workload-response.json"
  
  nex:
    deps: [proto]
    dir: cmd/nex
    cmds:
      - go build .
