global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - '127.0.0.1:8085'
