# https://taskfile.dev
# to install `go install github.com/go-task/task/v3/cmd/task@latest`

version: "3"

interval: 200ms

vars:
  NAME: "agentapi"

tasks:  

  gen:
    dir: .    
    cmds:
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/agent-api/register-agent-request=github.com/synadia-io/nex/agentapi/gen \
      --schema-output=https://github.com/synadia-io/nex/agent-api/register-agent-request=gen/register_agent_request.go \
       ../register-agent-request.json"
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/agent-api/start-workload-request=github.com/synadia-io/nex/agentapi/gen \
      --schema-output=https://github.com/synadia-io/nex/agent-api/start-workload-request=gen/start_workload_request.go \
       ../start-workload-request.json"
      - "go-jsonschema \
      --schema-package=https://github.com/synadia-io/nex/agent-api/stop-workload-request=github.com/synadia-io/nex/agentapi/gen \
      --schema-output=https://github.com/synadia-io/nex/agent-api/stop-workload-request=gen/stop_workload_request.go \
       ../stop-workload-request.json"
