# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint | Test | Build

on:
  pull_request:
    branches: [ "v3" ]

env:
  GO_VER: '1.23.0'
  GOPRIVATE: github.com/synadia-labs/oci-registry-nats
  GH_ACCESS_USER: ${{ secrets.GH_ACCESS_USER }}
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}


jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: GOPRIVATE Support
      run: git config --global url.https://${GH_ACCESS_USER}:${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
    - 
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}
        cache: false
    - 
      name: golangci-lint
      uses: golangci/golangci-lint-action@v6.1.0
      with:
        version: v1.61.0

  test:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: GOPRIVATE Support
      run: git config --global url.https://${GH_ACCESS_USER}:${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
    - 
      name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VER }}
    - 
      name: Run test suite | node
      run: |
        go test -v ./...
    - 
      name: Run test suite | CLI
      working-directory: ./cmd/nex
      run: |
        go test -v ./...
    - 
      name: Run test suite (rootfs | linux only)
      if: runner.os == 'Linux'
      working-directory: ./cmd/nex
      run: |
        sudo go test -v ./... -run TestRootFsSimple

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: GOPRIVATE Support
        run: git config --global url.https://${GH_ACCESS_USER}:${GH_ACCESS_TOKEN}@github.com/.insteadOf https://github.com/
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: build --clean --snapshot

