name: Release Candidate

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

env:
  GO_VER: '1.22.4'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "release-candidate"
  cancel-in-progress: false

jobs:
  release_candidate:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    concurrency:
      group: prerelease-installer-${{ github.ref }}
      cancel-in-progress: false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --verbose --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_RELEASE }}
